<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>Page Previewer</title>
        <link rel="stylesheet" href="assets/style.css" />
    </head>
    <body>
        <h1>Page Previewer</h1>
        <?php require "templates/".$page.".phtml"; ?>
        
        <script src="https://cdn.ckeditor.com/ckeditor5/35.0.1/classic/ckeditor.js"></script>
        <script type="application/javascript" src="assets/index.js"></script>
    </body>
</html>